# fly.toml app configuration file generated for dreamy-gardens-inspo on 2023-07-24T23:05:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dreamy-gardens-inspo"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
